### ISSUE TITLE
Incomplete Download

### ISSUE THREAD

**Issue by AArchLichKing** [Akianonymus/gdrive-downloader#7] opened 2020-10-10 05:05 UTC
Hi, 

Thanks for your work! I find that it sometimes works sometimes doesn't. And if it doesn'r work, I received the following output in linux screen. Can you please help me solve the issue? 
![image](https://user-images.githubusercontent.com/50974944/95646257-2f33f200-0af9-11eb-95ac-f6554c709e5f.png)

Thank you very much!

**Comment by Akianonymus** [comment] 2020-10-11 03:59
Well, it happens when it is not able to download properly.

Can you give me the link ?

I should probably add more logging to show what actually happened.

**Comment by AArchLichKing** [comment] 2020-10-11 07:33
Yeah, here is the link: https://drive.google.com/file/d/1zQt04MAj0ny16uWV6nuDwUSjbChGtQF6/view?usp=sharing
 Thx!

**Comment by AArchLichKing** [comment] 2020-10-11 07:33
Sometimes it works, sometimes it doesn't.

**Comment by Akianonymus** [comment] 2020-10-11 15:42
Well, in web browser also, i cannot download it, says qouta exceeded. And probably that's the main problem. If you can reproduce the issue with any other link, then it would be helpful.

**Comment by AArchLichKing** [comment] 2020-10-11 16:00
Oh, I guess that maybe the issue.

**Comment by Akianonymus** [comment] 2020-10-11 16:21
Well, closing the issue then, until you get the error again, and it's not because of qouta or any other problem given by google drive.

**Closed by Akianonymus** 2020-10-11 16:21 UTC
