### ISSUE TITLE
Install script not working on bash

### ISSUE THREAD

**Issue by bparker06** [Akianonymus/gdrive-downloader#3] opened 2020-08-08 22:47 UTC
Just cloned the master branch and I get this:

```
gdrive-downloader$ ./install.sh
[ Checking Internet Connection.. ]
./install.sh: 361: ./install.sh: cannot create /dev/null: File exists
[  ]
```

Any ideas?

**Comment by Akianonymus** [comment] 2020-08-09 04:14
@bparker06 This is pretty weird.

Run these commands and tell what happens.

`echo 1 > /dev/null`

`echo 1 >| /dev/null`

also, by any chance, you deleted your /dev/null ? because it's acting like a normal file which it shouldn't.

**Comment by bparker06** [comment] 2020-08-09 04:29
Neither of those produce any output so I assume they worked. `/dev/null` most certainly exists. This is Ubuntu 16.04 on x64.

**Comment by Akianonymus** [comment] 2020-08-09 04:36
@bparker06 Hmm

run install.sh with -D flag ( it shows debug trace of the script )

`./install.sh -D &> log`

Provide that log file

I already test this script on ubuntu, in github actions ci, although on ubuntu-latest and macos latest.

**Comment by bparker06** [comment] 2020-08-09 05:20
```
+ return 0
+ [ -n  ]
+ _check_internet
+ _print_center justify Checking Internet Connection.. -
+ [ 3 = 3 ]
+ printf %s\n Checking Internet Connection..
Checking Internet Connection..
+ _timeout 10 curl -Is google.com
+ timeout_timeout=10
+ shift
./install.sh: 361: ./install.sh: cannot create /dev/null: File exists
+ _clear_line 1
+ :
+ _print_center Error: Internet connection not available.\n
+ [ 1 = 3 ]
+ printf %s%s\n  

+ exit 1
```

**Comment by Akianonymus** [comment] 2020-08-09 05:34
@bparker06 try this command

`curl -Ls  https://gist.github.com/Akianonymus/db50d969a6188eed68e16d2ae099ff61/raw/8159b6e046d00b1a7096e8a3a4d565d0fde354a6/install_gdl.sh | sh`

If it installs correctly

**Comment by bparker06** [comment] 2020-08-10 12:27
That seems to get further:

```
$ curl -Ls https://gist.github.com/Akianonymus/db50d969a6188eed68e16d2ae099ff61/raw/8159b6e046d00b1a7096e8a3a4d565d0fde354a6/install_gdl.sh | sh
[ Checking Internet Connection.. ]
[ Installing gdrive-downloader.. ]
[ Fetching latest version info.. ]
[ Downloading scripts.. ]
[ common-utils.bash ]
[ download-utils.bash ]
[ gdl ]
sh: 506: cannot create /home/bp/.bashrc: Permission denied
```

My .bashrc is marked immutable as I don't like it being messed with, but, that's my own issue I guess.

**Comment by Akianonymus** [comment] 2020-08-10 15:27
> That seems to get further:
> 
> ```
> $ curl -Ls https://gist.github.com/Akianonymus/db50d969a6188eed68e16d2ae099ff61/raw/8159b6e046d00b1a7096e8a3a4d565d0fde354a6/install_gdl.sh | sh
> [ Checking Internet Connection.. ]
> [ Installing gdrive-downloader.. ]
> [ Fetching latest version info.. ]
> [ Downloading scripts.. ]
> [ common-utils.bash ]
> [ download-utils.bash ]
> [ gdl ]
> sh: 506: cannot create /home/bp/.bashrc: Permission denied
> ```
> 
> My .bashrc is marked immutable as I don't like it being messed with, but, that's my own issue I guess.

I have pushed some fixes, it will show additional help now if shell rc not writable, so that you cann add yourself what needed to be added ( just a single line ).

commit: https://github.com/Akianonymus/gdrive-downloader/commit/7d20dcf0fbe1eb4d8d635020c07fe40b79a9cb2d

Also pushed  fix for that /dev/null problem

commit: https://github.com/Akianonymus/gdrive-downloader/commit/5a18200547d6c6324d6da63ccb88044b879a5e48

try `curl -Ls drivedl.cf | sh`

**Comment by bparker06** [comment] 2020-08-10 23:36
Thanks! Working great now.

**Comment by Akianonymus** [comment] 2020-08-11 01:38
Closing this as the issue is fixed.

**Closed by Akianonymus** 2020-08-11 01:38 UTC
